apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: rg-dev-app
  namespace: rg-dev-app
  annotations:
    serviceoperator.azure.com/credential-from: rg-dev-app-aso-credentials
spec:
  location: eastus
---
apiVersion: keyvault.azure.com/v1api20210401preview
kind: Vault
metadata:
  name: app-keyvault-30473
  namespace: rg-dev-app
  annotations:
    serviceoperator.azure.com/credential-from: rg-dev-app-aso-credentials
spec:
  location: eastus
  owner:
    name: rg-dev-app
    kind: ResourceGroup
  properties:
    tenantId: feff82c9-b71b-493e-8246-f678e7bba4f6
    sku:
      family: "A"
      name: "standard"
    accessPolicies:
      - tenantId: feff82c9-b71b-493e-8246-f678e7bba4f6
        objectId: d53e5fa7-9032-4982-9055-5062c1e7f32e  # User or Service Principal Object ID
        permissions:
          secrets:
            - get
            - list
            - set
    enableSoftDelete: true
